<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>

    <UserSecretsId>dotnet-MantisBTMailTask-FB2209A4-FBA6-4B4A-9F04-E67F5790FF67</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11"/>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.11"/>
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.11"/>
    <PackageReference Include="Microsoft.Graph" Version="6.5.0" />
    <PackageReference Include="MySqlConnector" Version="2.6.2"/>
  </ItemGroup>
</Project>